title: "Hello, <br> I am Akash Yadav" # your name (or website title) here
logo: "/images/akash.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br> <p align="justify"> I am an enthusiast continuously working towards integrated intelligent systems.
                          I have worked on system design and integration with sensors like Camera, Radar, GPS etc. </p> <br>
                          <b> Educational Qualification </b>
                          <br> M.Sc    : Commercial Vehicle Technology 
                               M.Engg. : CAD/CAM/CAE <br>
                               B.Engg. : Mechanical Engineering <br>                 
                          <a href="https://www.linkedin.com/in/akash-yadav-10491/">View My LinkedIn Profile</a><br>
                          <a href="/Akash_Yadav_DL.pdf">Download CV</a>   

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
markdown: GFM
