title: "Hello, 
I am Akash Yadav" # your name (or website title) here
logo: "/images/akash.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br> I am an enthusiast continuously working towards integrated intelligent systems. 
  I have worked on system design and integration with sensors like Camera, Radar, GPS etc.
  Moreover, I have strong motivation and experience to understand papers and implement algorithms required by the use-case. <br>
  
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/akash-yadav-10491/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
